#!/bin/dash
# Basic system configuration and hardware setup
# (C) Klaus Knopper <knopper@knopper.net> 2004
# (C) 2003-2006 Joerg Schirottke <master@kanotix.com>
# (C) 2005-2007 Stefan Lippers-Hollmann <s.l-h@gmx.de>
# (C) 2007 Kel Modderman <kel@otaku42.de>

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

umask 022

# override tool behaviour through distro-defaults
FLL_DISTRO_MODE="installed"
FLL_IMAGE_DIR="SIDUX"
FLL_DISTRO_NAME="sidux"
FLL_MOUNTPOINT="/SIDUX"
FLL_LIVE_USER="sidux"
FLL_WALLPAPER="/usr/share/wallpapers/sidux.jpg"

X_CONF="/etc/X11/xorg.conf"

[ -r /etc/default/distro ] && . /etc/default/distro

[ ! "$FLL_DISTRO_MODE" = "live" ] && exit 0

[ -z "$FLL_MOUNTPOINT" ] && FLL_MOUNTPOINT="/$FLL_IMAGE_DIR"

case "$1" in
	start)
		;;
	stop)
		;;
	restart|force-reload)
		;;
esac

# Ignore these signals: INT, TERM, SEGV
trap "" 2 3 11

###############################################################################
# ANSI COLORS
###############################################################################
CRE="
[K"
NORMAL="[0;39m"

# RED: Failure or error message
RED="[1;31m"

# GREEN: Success message
GREEN="[1;32m"

# YELLOW: Descriptions
YELLOW="[1;33m"

# BLUE: System messages
BLUE="[1;34m"

# MAGENTA: Found devices or drivers
MAGENTA="[1;35m"

# CYAN: Questions
CYAN="[1;36m"

# BOLD WHITE: Hint
WHITE="[1;37m"

# get rid of these as soon as possible
HWSETUP_MAIN="/etc/sysconfig/knoppix"
HWSETUP_MOUSE="/etc/sysconfig/mouse"
HWSETUP_DESKTOP="/etc/sysconfig/desktop"

###############################################################################
# utility Functions
###############################################################################
# Simple shell grep
stringinfile()
{
	case "$(cat $2)" in
		*$1*)
			return 0
			;;
	esac

	return 1
}

# same for strings
stringinstring()
{
	case "$2" in 
		*$1*)
			return 0
			;;
	esac

	return 1
}

# Reread boot command line; echo last parameter's argument or return false.
getbootparam()
{
	stringinstring " $1=" "$CMDLINE" || return 1
	echo "$(echo $CMDLINE | sed -e s/.*$1=\\\(.*\\\)/\\1/ -e s/[[:space:]].*//)"

	return 0
}

# Check boot commandline for specified option
checkbootparam()
{
	stringinstring " $1" "$CMDLINE"
	return "$?"
}

start_service()
{
	if [ -x /etc/init.d/$1 ]; then
		if [ -n "$2" ]; then
			RUNLEVEL="$2" /etc/init.d/$1 start
		else
			/etc/init.d/$1 start
		fi
		return $?
	fi

	return 1
}

splash_progress()
{
	# be sure we are non-blocking
	if [ -p /etc/splashy/splashy.fifo ]; then
		(printf "progress $1\n" > /etc/splashy/splashy.fifo) &
	fi
}
### EOF utility functions

###############################################################################
#  mount critical virtual filesystems
###############################################################################
start_service mountkernfs.sh

# Read in boot parameters
[ -z "$CMDLINE" ] && CMDLINE=" $(cat /proc/cmdline)"

###############################################################################
# CD Checker
###############################################################################
if checkbootparam "testcd" || checkbootparam "testdvd"; then
	printf " ${BLUE}Checking CD data integrity as requested by '${CYAN}testcd${BLUE}' boot option.${NORMAL}\n"
	printf " ${BLUE}Reading files and checking against ${FLL_IMAGE_DIR}/md5sums, this may take a while...${NORMAL}\n"
	printf "${RED}"
	( cd /cdrom/ ; rm -f /tmp/md5sum.log ; LANG=C md5sum -c ${FLL_IMAGE_DIR}/md5sums 2>&1 | tee /tmp/md5sum.log )

	if grep -q FAILED /tmp/md5sum.log; then
		printf "${RED} *** CHECKSUM FAILED FOR THESE FILES:                          ***\n"
		egrep -v '(^md5sum:|OK$)' /tmp/md5sum.log
		printf "${RED} *** DATA ON YOUR CD MEDIUM IS POSSIBLY INCOMPLETE OR DAMAGED, ***${NORMAL}\n"
		printf "${RED} *** OR YOUR COMPUTER HAS BAD RAM.                             ***${NORMAL}\n"
		printf "${CYAN}Hit return to contine, or press the reset button to quit.${NORMAL} "
		read a
	else
		printf " ${GREEN}Everything looks OK${NORMAL}\n"
	fi
fi

###############################################################################
# Check if we are in interactive startup mode
###############################################################################
INTERACTIVE=""
stringinstring "BOOT_IMAGE=expert" "$CMDLINE" && INTERACTIVE="yes"

###############################################################################
# set hostname
###############################################################################
HOSTNAME="$(getbootparam 'hostname' 2>/dev/null)"
if [ -n "$HOSTNAME" ]; then
	rm -f /etc/hostname /etc/mailname
	printf "$HOSTNAME" > /etc/hostname
	printf "$HOSTNAME" > /etc/mailname
	# update /etc/hosts
	sed -i '/localhost/!s/^\(127.0.0.1[ \t]\+\)\(.\+\)$/\1'"$HOSTNAME"'/' /etc/hosts
fi

start_service hostname.sh

###############################################################################
# localization
###############################################################################
# Allow language specification via commandline. The default language
# will be overridden via "lang=de" boot commandline
LANGUAGE="$(getbootparam lang 2>/dev/null)"
[ -n "$LANGUAGE" ] || LANGUAGE="en"

# The default language/keyboard to use. This CANNOT be autoprobed.
# Most of these variables will be used to generate the KDE defaults
case "$LANGUAGE" in
	de)
		# German version UTF-8
		#LANGUAGE="de_DE:de"
		LANG="de_DE.UTF-8"
		KEYTABLE="de-latin1-nodeadkeys"
		KDEKEYBOARDS="de,us"
		XKBLAYOUT="de"
		TZ="Europe/Berlin"
		CD_COUNTRY="German"
		;;
	au)
		## Australian version
		#LANGUAGE="en_AU:en"
		LANG="en_AU.UTF-8"
		KEYTABLE="us"
		KDEKEYBOARDS="us"
		XKBLAYOUT="us"
		TZ="Australia/Sydney"
		CD_COUNTRY="us_american"
		;;
	bg)
		## Bulgarian version
		#LANGUAGE="bg_BG:bg"
		LANG="bg_BG.UTF-8"
		KEYTABLE="bg"
		KDEKEYBOARDS="bg,us"
		XKBLAYOUT="bg"
		TZ="Europe/Sofia"
		CD_COUNTRY="Bulgarian"
		;;
	br)
		## Brazilian Version
		#LANGUAGE="pt_BR:pt"
		LANG="pt_BR.UTF-8"
		KEYTABLE="br-abnt2"
		KDEKEYBOARDS="br,us"
		XKBLAYOUT="br"
		TZ="America/Sao_Paulo"
		CD_COUNTRY="Brazilian"
		;;
	ch)
		## Swiss version (basically de with some modifications)
		#LANGUAGE="de_CH:de"
		LANG="de_CH.UTF-8"
		KEYTABLE="sg-latin1"
		KDEKEYBOARDS="de_CH,de,fr,us"
		XKBLAYOUT="de"
		TZ="Europe/Zurich"
		CD_COUNTRY="Swiss-de"
		;;
	cn)
		## Simplified Chinese version
		LANG="zh_CN.UTF-8"
		KEYTABLE="us"
		KDEKEYBOARDS="us"
		XKBLAYOUT="us"
		TZ="Asia/Shanghai"
		CD_COUNTRY=""
		;;
	cs|cz)
		## Czech version
		#LANGUAGE="cs_CZ:cs"
		LANG="cs_CZ.UTF-8"
		KEYTABLE="cz-lat2"
		KDEKEYBOARDS="cs,us"
		XKBLAYOUT="cs"
		TZ="Europe/Prague"
		CD_COUNTRY="Czech-qwerty"
		;;
	dk|da)
		## Dansk version
		LANG="da_DK.UTF-8"
		KEYTABLE="dk"
		KDEKEYBOARDS="dk,us"
		XKBLAYOUT="dk"
		TZ="Europe/Copenhagen"
		CD_COUNTRY="Danish"
		;;
	el)
		## Greek version
		#LANGUAGE="el_GR:el"
		LANG="el_GR.UTF-8"
		KEYTABLE="gr"
		KDEKEYBOARDS="gr,us"
		XKBLAYOUT="gr"
		TZ="Europe/Athens"
		CD_COUNTRY="Greek"
		;;
	es)
		## Spanish version
		#LANGUAGE="es_ES:es"
		LANG="es_ES.UTF-8"
		KEYTABLE="es"
		KDEKEYBOARDS="es,us"
		XKBLAYOUT="es"
		TZ="Europe/Madrid"
		CD_COUNTRY="Spanish"
		;;
	fi)
		## Finnish version, though we may not have the kde-i18n files
		#LANGUAGE="fi_FI:fi"
		LANG="fi_FI.UTF-8"
		KEYTABLE="fi-latin1"
		KDEKEYBOARDS="fi,us"
		XKBLAYOUT="fi"
		TZ="Europe/Helsinki"
		CD_COUNTRY="Swedish"
		;;
	fr)
		## French version
		#LANGUAGE="fr_FR"
		LANG="fr_FR.UTF-8"
		KEYTABLE="fr"
		KDEKEYBOARDS="fr,us"
		XKBLAYOUT="fr"
		TZ="Europe/Paris"
		CD_COUNTRY="French"
		;;
	fr-be)
		## Belgian version
		#LANGUAGE="fr_BE:fr"
		LANG="fr_BE.UTF-8"
		KEYTABLE="be2-latin1"
		KDEKEYBOARDS="be,fr,us"
		XKBLAYOUT="be"
		TZ="Europe/Brussels"
		CD_COUNTRY="Belgian"
		;;
	ga)
		## Irish Gaeilge version
		LANG="ga_IE.UTF-8"
		KEYTABLE="uk"
		KDEKYBOARDS="ie"
		XKBLAYOUT="ie"
		TZ="Europe/Dublin"
		CD_COUNTRY="British"
		;;
	he|il)
		## Hebrew version
		#LANGUAGE="he_IL:he"
		LANG="he_IL.UTF-8"
		KEYTABLE="us"
		KDEKEYBOARDS="il,us"
		XKBLAYOUT="il"
		TZ="Asia/Jerusalem"
		CD_COUNTRY="Hebrew"
		;;
	hr)
		## Croatian version 
		#LANGUAGE=hr_HR:hr" 
		LANG="hr_HR.UTF-8" 
		KEYTABLE="hr" 
		KDEKEYBOARDS="hr,us"
		XKBLAYOUT="hr" 
		TZ="Europe/Zagreb" 
		CD_COUNTRY="Croatian"
		;;
	ie)
		## Irish (English) version
		#LANGUAGE="en_IE:en"
		LANG="en_IE.UTF-8"
		KEYTABLE="uk"
		KDEKEYBOARDS="ie,gb,us"
		XKBLAYOUT="ie"
		TZ="Europe/Dublin"
		CD_COUNTRY="British"
		;;
	it)
		## Italian version
		#LANGUAGE="it_IT"
		LANG="it_IT.UTF-8"
		KEYTABLE="it"
		KDEKEYBOARDS="it,us"
		XKBLAYOUT="it"
		TZ="Europe/Rome"
		CD_COUNTRY="Italian"
		;;
	ja)
		## (limited) Japanese version
		#LANGUAGE="ja_JP:ja"
		LANG="ja_JP.UTF-8"
		KEYTABLE="us"
		KDEKEYBOARDS="jp,us"
		XKBLAYOUT="jp"
		TZ="Asia/Tokyo"
		CD_COUNTRY="Japanese"
		;;
	nl)
		## Dutch version
		#LANGUAGE="nl_NL:nl"
		LANG="nl_NL.UTF-8"
		KEYTABLE="us"
		KDEKEYBOARDS="nl,us"
		XKBLAYOUT="nl"
		TZ="Europe/Amsterdam"
		CD_COUNTRY="Dutch"
		;;
	nl-be)
		## Belgian version
		#LANGUAGE="nl_BE:nl"
		LANG="nl_BE.UTF-8"
		KEYTABLE="be2-latin1"
		KDEKEYBOARDS="be,fr,us"
		XKBLAYOUT="be"
		TZ="Europe/Brussels"
		CD_COUNTRY="Belgian"
		;;
	pl)
		## Polish version
		#LANGUAGE="pl_PL:pl"
		LANG="pl_PL.UTF-8"
		KEYTABLE="pl"
		KDEKEYBOARDS="pl,us"
		XKBLAYOUT="pl"
		TZ="Europe/Warsaw"
		CD_COUNTRY="Polish"
		;;
	pt)
		## Portuguese version
		#LANGUAGE="pt_PT:pt"
		LANG="pt_PT.UTF-8"
		KEYTABLE="pt-latin1"
		KDEKEYBOARDS="pt,us"
		XKBLAYOUT="pt"
		TZ="Europe/Lisbon"
		CD_COUNTRY="Portugese"
		;;
	ru)
		## Russian version
		#LANGUAGE="ru_RU:ru"
		LANG="ru_RU.UTF-8"
		KEYTABLE="ru"
		KDEKEYBOARDS="ru,us"
		XKBLAYOUT="ru"
		TZ="Europe/Moscow"
		CD_COUNTRY="Russian"
		;;
	sk)
		## Slovak version (guessed)
		#LANGUAGE="sk_SK:sk"
		LANG="sk_SK.UTF-8"
		KEYTABLE="sk-qwerty"
		KDEKEYBOARDS="sk,us"
		XKBLAYOUT="sk"
		TZ="Europe/Bratislava"
		CD_COUNTRY="Slovak-qwerty"
		;;
	sl)
		## Slovenian keyboard
		#LANGUAGE="sl_SI:sl"
		LANG="sl_SI.UTF-8"
		KEYTABLE="slovene"
		KDEKEYBOARDS="si,us"
		XKBLAYOUT="si"
		TZ="Europe/Ljubljana"
		#CONSOLEFONT="iso02g"
		CD_COUNTRY="Slovene"
		;;
	tr)
		## Turkish version (guessed)
		#LANGUAGE="tr_TR"
		LANG="tr_TR.UTF-8"
		KEYTABLE="tr_q-latin5"
		KDEKEYBOARDS="tr,us"
		XKBLAYOUT="tr"
		TZ="Europe/Istanbul"
		CD_COUNTRY="Turkish"
		;;
	tw)
		## Traditional Chinese version (thanks to Chung-Yen Chang)
		#LANGUAGE="zh_TW:zh"
		LANG="zh_TW.UTF-8"
		KEYTABLE="us"
		KDEKEYBOARDS="us"
		XKBLAYOUT="us"
		TZ="Asia/Taipei"
		CD_COUNTRY=""
		;;
	uk)
		## British version UTF-8
		#LANGUAGE="en_GB:en"
		LANG="en_GB.UTF-8"
		KEYTABLE="uk"
		KDEKEYBOARDS="gb,us"
		XKBLAYOUT="gb"
		TZ="Europe/London"
		CD_COUNTRY="British"
		;;
	us)
		# American version UTF-8
		#LANGUAGE="en_US:en"
		LANG="en_US.UTF-8"
		KEYTABLE="us"
		KDEKEYBOARDS="us,ca"
		XKBLAYOUT="us"
		TZ="America/New_York"
		CD_COUNTRY="us_american"
		;;
	*)
		# American version UTF-8
		#LANGUAGE="en_US:en"
		LANG="en_US.UTF-8"
		KEYTABLE="us"
		KDEKEYBOARDS="us,ca"
		XKBLAYOUT="us"
		TZ="Europe/London"
		CD_COUNTRY="us_american"
		;;
esac

export LANG

###############################################################################
# update locale settings
###############################################################################
# ensure that /etc/default/locale is an ordinary file and not a symlink
rm -f /etc/default/locale
# write locale
update-locale "LANG=$LANG"

###############################################################################
# Set KDE i18n Keyboard
###############################################################################
if grep -q ^KDEKEYBOARDS /etc/default/distro 2>/dev/null; then
	sed -i -e 's/^FLL_KDEKEYBOARDS=.*$/FLL_KDEKEYBOARDS='"$KDEKEYBOARDS"'/' \
			/etc/default/distro
else
	printf "\n# kde i18n settings\n"		>> /etc/default/distro
	printf "FLL_KDEKEYBOARDS=\"$KDEKEYBOARDS\"\n" 	>> /etc/default/distro
fi

###############################################################################
# for console-data
###############################################################################
case $CD_COUNTRY in
	French)
		#Issue
		CD_FAMILY="azerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Same as X11 (latin 9)"
		CD_FULL="$CD_COUNTRY"
		;;
	Belgian)
		CD_FAMILY="azerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	us_american)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="US american"
		;;
	British)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Bulgarian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Byelorussian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Brazilian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Canadian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="English"
		CD_FULL="$CD_COUNTRY"
		;;
	Canadian-fr)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="French"
		CD_FULL="$CD_COUNTRY"
		;;
	Czech-qwerty)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Danish)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Spanish)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Estonian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Finnish)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Polish)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Greek)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Italian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Lithuanian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Latvian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Norwegian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Japanese)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Dutch)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Hebrew)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Hungarian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Icelandic)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Latin_American)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="Latin American"
		;;
	Macedonian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Portugese)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Romanian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Russian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Serbian-qwerty)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Swedish)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Slovak-qwerty)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Thai)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Turkish)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Ukrainian)
		CD_FAMILY="qwerty"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Swiss-fr)
		CD_FAMILY="qwertz"
		CD_KEYMAP="Standard"
		CD_VARIANT="French"
		CD_FULL="$CD_COUNTRY"
		;;
	Swiss-de)
		CD_FAMILY="qwertz"
		CD_KEYMAP="Standard"
		CD_VARIANT="German"
		CD_FULL="German"
		;;
	German)
		CD_FAMILY="qwertz"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Slovak-qwertz)
		CD_FAMILY="qwertz"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Czech-qwertz)
		CD_FAMILY="qwertz"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Hungarian)
		CD_FAMILY="qwertz"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Slovene)
		CD_FAMILY="qwertz"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Croat)
		CD_FAMILY="qwertz"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	Serbian-qwertz)
		CD_FAMILY="qwertz"
		CD_KEYMAP="Standard"
		CD_VARIANT="Standard"
		CD_FULL="$CD_COUNTRY"
		;;
	*)
		CD_FAMILY="qwerty"
		CD_KEYMAP="us"
		CD_VARIANT="Standard"
		CD_FULL="US american"
		;;
esac

CD_LAYOUT="$(echo $CD_COUNTRY | cut -d'-' -f1)"
CD_LAYOUT_PATH="$(echo $CD_COUNTRY | tr [A-Z] [a-z] | cut -d'-' -f1)"
CD_FULL_FIX="$(echo $CD_FULL | cut -d'-' -f1)"
CD_VARIANT_PATH="$(echo $CD_VARIANT | tr [A-Z] [a-z])"

echo "locales locales/default_environment_locale select $LANG \
console-data console-data/keymap/policy select Select keymap from arch list \
console-data console-data/keymap/family select $CD_FAMILY \
console-data console-data/keymap/$CD_FAMILY/layout select $CD_FULL_FIX \
console-data console-data/keymap/$CD_FAMILY/$CD_LAYOUT_PATH/variant select $CD_VARIANT \
console-data console-data/keymap/$CD_FAMILY/$CD_LAYOUT_PATH/$CD_VARIANT_PATH/keymap select $CD_KEYMAP \
console-data console-data/keymap/full select $CD_FULL" | /usr/bin/debconf-set-selections

###############################################################################
# / must be read-write in any case, starting from here
###############################################################################
mount -o remount,rw / 2>/dev/null

###############################################################################
# begin hardware detection and autoconfiguration
###############################################################################
printf " ${GREEN}Enabling ${YELLOW}udev${GREEN} device and hotplug management daemon.${NORMAL}\n"

# start udev
start_service udev S

# mount special filesystems under /dev
start_service mountdevsubfs.sh

###############################################################################
# setup console-data (before interactive setup stage)
###############################################################################
printf "${BLUE}Configuring console for a ${YELLOW}${KEYTABLE} keymap${BLUE}...${NORMAL}\n"

# install keymap
/usr/sbin/install-keymap "$KEYTABLE"

# try this, it takes care of unicode start
start_service keymap.sh

###############################################################################
# update mtab
###############################################################################
start_service mtab.sh
start_service udev-mtab S

###############################################################################
#  Set clock (Local time is more often used than GMT, so it is default)
###############################################################################
if checkbootparam utc >/dev/null 2>&1 || checkbootparam gmt >/dev/null 2>&1; then
	[ -w /etc/default/rcS ] && sed -i 's/^UTC=.*/UTC=yes/' /etc/default/rcS
	TZ="UTC"
else
	[ -w /etc/default/rcS ] && sed -i 's/^UTC=.*/UTC=no/' /etc/default/rcS
fi

if checkbootparam tz >/dev/null 2>&1; then
	TZ="$(getbootparam tz 2>/dev/null)"
fi

[ -n "$TZ" ] || TZ="UTC"

if [ -f "/usr/share/zoneinfo/$TZ" ]; then
	# /etc/localtime is excluded at build time
	cp "/usr/share/zoneinfo/$TZ" /etc/localtime
	printf "$TZ" > /etc/timezone
fi

start_service hwclock.sh >/dev/null

###############################################################################
# hwsetup
###############################################################################
# Delete obsolete links and files before starting autoconfig
if ! checkbootparam "nohwsetup"; then
	rm -f "$HWSETUP_MAIN" 2>/dev/null
fi

# FIXME: Also read desired desktop, if any (not implemented right now)
DESKTOP="$(getbootparam desktop 2>/dev/null)"
# Allow only supported windowmanagers
case "$DESKTOP" in
	gnome|enlightenment|kde|larswm|xfce|xfce4|windowmaker|wmaker|icewm|fluxbox|twm|nx|rdp|kiosk)
		;;
	*)
		DESKTOP="kde"
		;;
esac

CUSTOM_DPI="$(getbootparam dpi 2>/dev/null)"

# Second: Search & configure supported hardware
# Check for options relevant to hwsetup
NOSERIAL=""
checkbootparam noserial >/dev/null 2>&1 && NOSERIAL="yes"
[ -n "$NOSERIAL" ] && HWSETUP_NOSERIAL="-m"
# load serial module
modprobe 8250 >/dev/null 2>&1

# load psmouse module
modprobe psmouse >/dev/null 2>&1
printf "${WHITE}"
if hwsetup $HWSETUP_NOSERIAL >/dev/null; then
	printf "${NORMAL}"
else
	printf " ${RED}Please check.${NORMAL}\n"
fi

# activate PC Speaker
modprobe pcspkr >/dev/null 2>&1

# activate input driver for char event devices
modprobe evdev >/dev/null 2>&1

# Handle special options for ALSA sound drivers
rm -f /etc/modprobe.d/alsa-special
SYS=$(cut -f2 -d: /sys/devices/pci*/{,*/}*/modalias 2>/dev/null)
ALSA_SPECIAL=""
for sysid in $SYS; do
	# ALSA_SPECIAL is [kernel module with _ not -] [needed options]
	case "$sysid" in
		v000010DEd0000026Csv00001043sd000081CBbc*)
			# ASUS M2NPV-VM
			ALSA_SPECIAL="snd_hda_intel position_fix=1 model=3stack"
			break
			;;
		v00008086d000027D8sv00001854sd0000005Fbc*)
			# LG Electronics P1-J302E1
			ALSA_SPECIAL="snd_hda_intel model=lg"
			break
			;;
		v00008086d0000284Bsv00008086sd0000284Bbc*)
			# MSI MS-7235
			ALSA_SPECIAL="snd_hda_intel position_fix=1"
			break
			;;
	esac
done
if [ -n "$ALSA_SPECIAL" ]; then
	printf "options $ALSA_SPECIAL\n" > /etc/modprobe.d/alsa-special
	if [ -d "/sys/module/${ALSA_SPECIAL%% *}" ]; then
		rmmod "${ALSA_SPECIAL%% *}"
		modprobe "$ALSA_SPECIAL"
	fi
fi

# Read in what hwsetup has found
[ -f "$HWSETUP_MAIN" ] && . "$HWSETUP_MAIN"

# Workaround for new mouse detection
if [ -f "$HWSETUP_MOUSE" ]; then
	. "$HWSETUP_MOUSE"
	if [ "$MOUSETYPE" = "ps2" ]; then
		ln -sf /dev/psaux /dev/mouse
		perl -pi -e "s|/dev/input/mice|/dev/psaux|" "$HWSETUP_MOUSE" "$HWSETUP_MAIN"
		. "$HWSETUP_MOUSE"
		. "$HWSETUP_MAIN"
	fi
fi
       
# Mouse
if [ -n "$MOUSE_DEVICE" ]; then
	printf " ${GREEN}Mouse is ${YELLOW}${MOUSE_FULLNAME}${GREEN} at ${MAGENTA}${MOUSE_DEVICE}${NORMAL}\n"
fi

# Soundcard
if [ -n "$SOUND_FULLNAME" -o -n "$SOUND_DRIVER" ]; then
	SOUNDCARD="$SOUND_DRIVER"
	printf " ${GREEN}Soundcard is"
	[ -n "$SOUND_FULLNAME" ] && printf " ${YELLOW}$SOUND_FULLNAME${GREEN}"
	[ -n "$SOUNDCARD" ] && printf ", ALSA module is ${MAGENTA}$SOUNDCARD${GREEN}"
	printf "${NORMAL}\n"
fi

# Get max. sound volume
VOL="$(getbootparam vol 2>/dev/null)"
if [ -z "$VOL" ] || [ "$VOL" -lt 0 ] || [ "$VOL" -gt 100 ]; then
	VOL=50
fi

# Fast ALSA detection
case "$SOUND_DRIVER" in
	snd*)
		printf "alias snd-card-0 $SOUND_DRIVER\n"  > /etc/modprobe.d/sound
		printf "options $SOUND_DRIVER index=0\n"  >> /etc/modprobe.d/sound
		#set_mixers
		aumix -m 0 -v $VOL -w $VOL -c $VOL >/dev/null 2>&1
		;;
esac

###############################################################################
# misc. hardware detections/workarounds
###############################################################################
# dwl520e1 detection
if lspci -nv|grep 1260:3873 -A1|grep -q 1186:3700; then
	/usr/sbin/dwl520e1_fw_load >/dev/null 2>&1
	printf "install hostap_pci /sbin/modprobe --ignore-install hostap_pci && /usr/sbin/dwl520e1_fw_load >/dev/null 2>&1\n" > \
		/etc/modprobe.d/dwl520e1
fi

# soft modem detection
if ! checkbootparam "nomodem"; then
	if lspci | grep Intel | grep -q "AC'97 Modem Controller"; then
		start_service sl-modem-daemon >/dev/null
	fi
fi

# Start FC detection on vt10
NOFC=""
if [ -x /usr/sbin/detect-fc ]; then
	checkbootparam "nofc" && NOFC="yes"
	[ -e /etc/drdsl/modules.inc ] && NOFC="yes"
	if [ -z "$NOFC" ]; then
		printf " ${GREEN}Starting ${YELLOW}FC${GREEN} detection on ${YELLOW}vt10${GREEN}.${NORMAL}\n"
		open -c 10 /usr/sbin/detect-fc
	fi
fi

###############################################################################
# load required modules
###############################################################################
# Load fuse module
if [ -x /etc/init.d/fuse-utils ]; then
	start_service fuse-utils >/dev/null
else
	modprobe fuse >/dev/null 2>&1
fi

# load capability LSM (needed for hal)
modprobe capability >/dev/null 2>&1

###############################################################################
# automatic X Setup
###############################################################################
if ! checkbootparam "nomkxf86config"; then
	[ -x /usr/sbin/mkxf86config ] && /usr/sbin/mkxf86config
fi

# Read in changes
[ -f "$HWSETUP_MAIN" ] && . "$HWSETUP_MAIN"

if [ -f /etc/X11/xorg.conf ]; then
	# Apply Language Settings for xorg
	sed -i "s|\"XkbLayout\".*$|\"XkbLayout\"\t\"${XKBLAYOUT}\"|" /etc/X11/xorg.conf
fi

###############################################################################
# partition detection and autoconfiguration of /etc/fstab and /media/*
###############################################################################
if checkbootparam "nofstab"; then
	printf " ${BLUE}Skipping /etc/fstab creation as requested on boot commandline.${NORMAL}\n"
else
	printf "${BLUE}Scanning for Harddisk partitions and creating ${YELLOW}/etc/fstab${BLUE}..."
	
	/usr/sbin/rebuildfstab --quiet --write-fstab --make-mountpoints --user "$FLL_LIVE_USER" \
		--group "$(getent passwd "$FLL_LIVE_USER" | cut -d\: -f 4)"
	
	printf "${BLUE}Done.${NORMAL}\n"

	if checkbootparam "noswap"; then
		printf "${BLUE}Ignoring swap partitions as requested.${NORMAL}\n"
	else
		swapon -a -e
	fi
fi

###############################################################################
# Fat-Client-Version: DHCP Broadcast for IP address
###############################################################################
if checkbootparam "nodhcp"; then
	printf " ${BLUE}Skipping DHCP broadcast/network detection as requested on boot commandline.${NORMAL}\n"
else
	NETDEVICES=$(perl -le 'print for map {s/.*\///; grep( !/^(lo|br|sit)\d*/,$_);} </sys/class/net/*>')
	if [ -n "$NETDEVICES" ]; then
		CONNETDEVS=""
		for DEVICE in $NETDEVICES; do
			# wireless
			[ -d /sys/class/net/${DEVICE}/wireless ] && continue
			if [ -f /sys/class/net/${DEVICE}/addr_len ]; then
				# unwanted: > 6 byte mac length (eg, placeholder interface, eth1394)
				[ "$(cat /sys/class/net/${DEVICE}/addr_len)" -gt 6 ] && continue
			fi
			
			if ifconfig "$DEVICE" up; then
				sleep 2
				
				# probe for link beat
				ifplugstatus --quiet "$DEVICE"
			
				# link beat detected ?
				if [ "$?" = "2" ]; then
					CONNETDEVS="$CONNETDEVS $DEVICE"
					printf "\nallow-hotplug $DEVICE\n"	>> /etc/network/interfaces
					printf "iface $DEVICE inet dhcp\n"	>> /etc/network/interfaces
				else
					ifconfig "$DEVICE" down
				fi
			fi
		done
		
		if [ -n "$CONNETDEVS" ]; then
			printf " ${GREEN}Starting ${YELLOW}DHCP${GREEN} broadcast on ethernet devices:${NORMAL}"
			printf "${MAGENTA}${CONNETDEVS}${GREEN}.${NORMAL}\n"
		fi

		start_service ifupdown >/dev/null
		# networking also starts the lo (loopback) interface, background it
		( start_service networking  >/dev/null 2>&1 ) &
	fi
fi

###############################################################################
# power management
###############################################################################
PBIOS=
PSERV=
if [ -d /proc/acpi ]; then
	# ACPI
	if checkbootparam "noacpi"; then
		printf " ${BLUE}Skipping ACPI bios detection as requested on boot commandline.${NORMAL}\n"
	else
		fuser -k /proc/acpi/event >/dev/null 2>&1
		PBIOS=ACPI
		PSERV=acpid
	fi
else
	# APM
	if checkbootparam "noapm"; then
		printf " ${BLUE}Skipping APM bios detection as requested on boot commandline.${NORMAL}\n"
	else
		PBIOS=APM
		PSERV=apmd
	fi
fi

if [ -n "$PBIOS" ] && [ -x /etc/init.d/"$PSERV" ]; then
	printf " ${GREEN}${PBIOS} bios found, activating power management:${NORMAL}"
	if start_service "$PSERV" >/dev/null; then
		printf " ${MAGENTA}${PSERV}${GREEN}.${NORMAL}\n"
	else
		printf " ${RED}Failed!${NORMAL}\n"
	fi
fi

###############################################################################
# enable dbus & hald
###############################################################################
if [ -x /etc/init.d/dbus ]; then
	if checkbootparam "nodbus"; then
		printf " ${BLUE}Not starting D-Bus/HAL as requested on boot commandline.${NORMAL}\n"
	else
		printf " ${GREEN}Enabling D-Bus and Hardware Abstraction Layer:${NORMAL}"
		if start_service dbus >/dev/null; then
			printf " ${MAGENTA}dbus${GREEN}.${NORMAL}\n"
			start_service /etc/init.d/avahi-daemon >/dev/null
		else
			printf " ${RED}Failed!${NORMAL}\n"
		fi
	fi
fi

###############################################################################
# laptop?
###############################################################################
unset IS_LAPTOP
if laptop-detect 2>/dev/null; then
	IS_LAPTOP=true
fi

###############################################################################
# cpufreq detection
###############################################################################
if checkbootparam "nocpufreq" || checkbootparam "noacpi"; then
	printf " ${BLUE}Skipping CPUfreq detection as requested on boot commandline.${NORMAL}\n"
else
	unset CPUFREQ CPUSERV

	# cpufreq detection from ubuntu powernowd, exports `CPUFREQ' on successful detection
	if [ -f /usr/share/initscripts-sidux-live/cpufreq-detect ]; then
		. /usr/share/initscripts-sidux-live/cpufreq-detect
		
		# attempt load the detected cpufreq module
		if [ -n "$CPUFREQ" ]; then
			if modprobe "$CPUFREQ" 2>/dev/null; then
				# start cpufreq power services
				:
			else
				unset CPUFREQ
			fi
		fi
		
		# always try acpi-cpufreq as fallback when acpi support is present
		if [ -z "$CPUFREQ" ] && [ -d /proc/acpi ]; then
			if modprobe acpi-cpufreq 2>/dev/null; then
				CPUFREQ=acpi-cpufreq
			fi
		fi
	fi

	# start power management service
	if [ -n "$CPUFREQ" ]; then
		printf " ${GREEN}Activating ${YELLOW}${CPUFREQ}${GREEN} CPUfreq management:${NORMAL}"
		
		# hack to disable suspend, it currently does not mix with live-mode
		# kpowersave exposes this problem to unsuspecting users
		if [ -w /etc/powersave/sleep ]; then
			sed -i 's/^\(DISABLE_USER_SUSPEND2.*\)=.*$/\1="yes"/' /etc/powersave/sleep
		fi

		# preseed powersaved with the correct cpufreq module name (avoid re-detection)
		if [ -w /etc/powersave/cpufreq ]; then
			sed -i 's/^\(CPUFREQD_MODULE\)=.*$/\1="'$CPUFREQ'"/' /etc/powersave/cpufreq
		fi

		# start power management, powersaved is given preference
		if start_service powersaved >/dev/null; then
			CPUSERV=powersaved
		elif start_service powernowd >/dev/null; then
			CPUSERV=powernowd
		else
			printf " ${RED}Failed!${NORMAL}\n"
		fi

		# announce the service
		if [ -n "$CPUSERV" ]; then
			printf " ${MAGENTA}${CPUSERV}${GREEN}.${NORMAL}\n"
		fi
	fi
fi

###############################################################################
# bluetooth
###############################################################################
if [ -x /etc/init.d/bluetooth ]; then
	if checkbootparam "nobluetooth"; then
		printf " ${BLUE}Skipping bluetooth detection as requested on boot commandline.${NORMAL}\n"
	else
		BLUETOOTH="$(hwinfo --bluetooth | awk '/Hardware Class:/{ print $NF; exit }' 2>/dev/null)"
		if [ "$BLUETOOTH" = bluetooth ] && start_service bluetooth >/dev/null 2>&1; then
			printf " ${GREEN}Starting services for ${YELLOW}bluetooth${GREEN} support.${NORMAL}\n"
		fi
	fi
fi

###############################################################################
# keyboard keycodes
###############################################################################
start_service hotkey-setup >/dev/null 2>&1

###############################################################################
# do laptop specific stuff
###############################################################################
if [ -n "$IS_LAPTOP" ]; then
	# acpi-support
	if pidof acpid >/dev/null && start_service acpi-support >/dev/null 2>&1; then
		printf " ${GREEN}Starting ${YELLOW}acpi-support${GREEN} subsystem.${NORMAL}\n"
	fi
fi

###############################################################################
# configure $HOME
###############################################################################

# Copy profiles if not already present
# modified to pull entire /etc/skel and /usr/share/user-profile/profile folder contents,
# depending on ramdisk space constraints
FLL_LIVE_USER_HOME="$(getent passwd $FLL_LIVE_USER | cut -d\: -f 6)"

printf "${BLUE}Populate ${YELLOW}${FLL_LIVE_USER_HOME}${BLUE} with user configurations...${NORMAL}"

mkdir -p "${FLL_LIVE_USER_HOME}"

# make sure live-user is owner of their /home
chown "${FLL_LIVE_USER}:${FLL_LIVE_USER}" "${FLL_LIVE_USER_HOME}"

rsync -Ha --ignore-existing /etc/skel/ "${FLL_LIVE_USER_HOME}/" 2>/dev/null
rsync -Ha --ignore-existing /usr/share/user-profile/profile/ "${FLL_LIVE_USER_HOME}/" 2>/dev/null

# add aliases for sudo and su
grep alias\ su  "${FLL_LIVE_USER_HOME}/.bashrc" > /dev/null || printf "alias su=\"sudo su\"\n"   >> "${FLL_LIVE_USER_HOME}/.bashrc"
grep alias\ sux "/home/$FLL_LIVE_USER/.bashrc"  > /dev/null || printf "alias sux=\"sudo sux\"\n" >> "${FLL_LIVE_USER_HOME}/.bashrc"

# configure kdesu to use sudo for the live user
if [ -x /usr/bin/kde-config ] && [ ! -r /home/$FLL_LIVE_USER/.kde/share/config/kdesurc ] ; then
	mkdir -p "/home/${FLL_LIVE_USER}/.kde/share/config/"
	printf "[super-user-command]\n"		 > "/home/${FLL_LIVE_USER}/.kde/share/config/kdesurc"
	printf "super-user-command=sudo\n"	>> "/home/${FLL_LIVE_USER}/.kde/share/config/kdesurc"
fi

# Share Mozilla plugins with Firefox
if [ -x /usr/bin/iceweasel ]; then
	MOZPROFILE=$(awk '/Profile/{if (/Profile0/){inprof=1}else{inprof=0}}/Path/{if(inprof){print;}}' ${FLL_LIVE_USER_HOME}/.mozilla/firefox/profiles.ini | sed 's/^Path\=//' )
	NEWMOZPROFILE=$(mawk 'BEGIN{print int(10000000 * rand())}')".default"
	
	mv -f "${FLL_LIVE_USER_HOME}/.mozilla/firefox/${MOZPROFILE}" "${FLL_LIVE_USER_HOME}/.mozilla/firefox/${NEWMOZPROFILE}" && \
		sed -i 's/Path='$MOZPROFILE'/Path='$NEWMOZPROFILE'/' "${FLL_LIVE_USER_HOME}/.mozilla/firefox/profiles.ini"
fi

if [ -n "$LANGUAGE" ]; then
	# Set mozilla's preferred language
	for f in `ls -1 ${FLL_LIVE_USER_HOME}/.mozilla/*/*/prefs.js 2>/dev/null`; do
		echo 'user_pref("intl.accept_languages", "'"$LANGUAGE"', en");' >>"$f"
		
		case "$LANG" in
			de*|at*|ch*)
				echo 'user_pref("general.useragent.contentlocale", "AT");' >>"$f"
				echo 'user_pref("general.useragent.locale", "de-AT");' >>"$f" ;;
		esac
		# else leave default language
	done

	for f in `ls -1 ${FLL_LIVE_USER_HOME}/.mozilla/*/*/chrome/chrome.rdf.${LANGUAGE} 2>/dev/null`; do
		\mv -f "$f" "${f%%.${LANGUAGE}}"
	done
fi

if [ ! -r "${FLL_LIVE_USER_HOME}/.kde/share/config/kdeglobals" ]; then
	# Only regenerate the config and Desktop files if missing
	mkdir -p	"${FLL_LIVE_USER_HOME}/.kde/share" \
			"${FLL_LIVE_USER_HOME}/Desktop"
	
	rm -f "${FLL_LIVE_USER_HOME}/.kde/Autostart/sorticons.desktop"
fi

# Check for /index.html (_en), or KNOPPIX/index.html (_en) on this CD
if [ -e /cdrom/index.html ]; then
	INDEXFILE="/cdrom/index.html"
else
	for i in index ${FLL_IMAGE_DIR}/index; do
		INDEXFILEDE="/cdrom/${i}.html"
		INDEXFILEEN="/cdrom/${i}_en.html"
		[ -e "$INDEXFILEEN" ] && INDEXFILE="$INDEXFILEEN" && [ "$LANGUAGE" != "de" ] && break
		[ -e "$INDEXFILEDE" ] && INDEXFILE="$INDEXFILEDE" && [ "$LANGUAGE"  = "de" ] && break
	done
fi

if [ -e "$INDEXFILE" ]; then
	cat >> "${FLL_LIVE_USER_HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" <<EOF
[Desktop Entry]
Name=$FLL_CDROM_INDEX
# Exec=kfmclient openProfile webbrowsing $INDEXFILE
Exec=konqueror --geometry 950x700+35+20 file:$INDEXFILE
Type=Application
Icon=$FLL_CDROM_INDEX_ICON
Terminal=0
EOF
	if ! checkbootparam "nointro"; then
		mkdir -p $FLL_LIVE_USER_HOME/.kde/Autostart
		ln "${FLL_LIVE_USER_HOME}/Desktop/${FLL_DISTRO_NAME}.desktop" "${FLL_LIVE_USER_HOME}/.kde/Autostart/showindex.desktop"
	fi
fi

# Setup language/keyboard
[ -d "${FLL_LIVE_USER_HOME}/.kde/share/config" ] || mkdir -p "${FLL_LIVE_USER_HOME}/.kde/share/config"

if [ -r "${FLL_LIVE_USER_HOME}/.kde/share/config/kdeglobals" ]; then
	# Apply Language Settings for KDE
	touch "${FLL_LIVE_USER_HOME}/.kde/share/config/kdeglobals"
	sed -i	-e 's/^Charset=.*$/Charset='"$CHARSET"'/' \
		-e 's/^Country=.*$/Country='"$COUNTRY"'/' \
		-e 's/^Language=.*$/Language='"$LANGUAGE"'/' \
			"${FLL_LIVE_USER_HOME}/.kde/share/config/kdeglobals"
	
	touch "${FLL_LIVE_USER_HOME}/.kde/share/config/kxkbrc"
	sed -i "s|^LayoutList.*$|LayoutList=${KDEKEYBOARDS}|" "${FLL_LIVE_USER_HOME}/.kde/share/config/kxkbrc"

	# set KDE wallpaper
	touch "${FLL_LIVE_USER_HOME}/.kde/share/config/kdeglobals"
	sed -i 's|Wallpaper=.*$|Wallpaper='"$FLL_WALLPAPER"'|g' "${FLL_LIVE_USER_HOME}/.kde/share/config/kdesktoprc"

	# Check for custom splashscreen in /cdrom/${FLL_IMAGE_DIR}/
	if [ -d "/cdrom/${FLL_IMAGE_DIR}/ksplash" ]; then
		[ -d "${FLL_LIVE_USER_HOME}/.kde/share/apps" ] || mkdir -p "${FLL_LIVE_USER_HOME}/.kde/share/apps"
		ln -s "/cdrom/${FLL_IMAGE_DIR}/ksplash" "${FLL_LIVE_USER_HOME}/.kde/share/apps/"
	fi
fi

if [ ! -r "${FLL_LIVE_USER_HOME}/.kde/share/config/startupconfigkeys" ]; then
	# see kstartupconfig source for usage
	mkdir -m 700 -p	"${FLL_LIVE_USER_HOME}/.kde" \
			"${FLL_LIVE_USER_HOME}/.kde/share" \
			"${FLL_LIVE_USER_HOME}/.kde/share/config"
	
	cat > "${FLL_LIVE_USER_HOME}/.kde/share/config/startupconfigkeys" <<EOF
kcminputrc Mouse cursorTheme ''
kcminputrc Mouse cursorSize ''
kpersonalizerrc General FirstLogin false
ksplashrc KSplash Theme Default
kcmrandrrc Display ApplyOnStartup false
kcmrandrrc [Screen0]
kcmrandrrc [Screen1]
kcmrandrrc [Screen2]
kcmrandrrc [Screen3]
kcmfonts General forceFontDPI 0
EOF
fi

# fix permissions
chown -R "$FLL_LIVE_USER":"$FLL_LIVE_USER" "${FLL_LIVE_USER_HOME}"

printf "${BLUE}Done.${NORMAL}\n"

###############################################################################
# set up X.org
###############################################################################
if start_service x11-common S; then
	printf "${BLUE}Set up X sockets...${NORMAL}\n"
fi

if [ -x /usr/bin/kdm ]; then
	cp --remove-destination "${FLL_MOUNTPOINT}/etc/kde3/kdm/kdmrc" /etc/kde3/kdm/kdmrc

	KDM_OVERRIDE_DIR="/etc/default/kdm.d/"
	KDM_THEME="/usr/share/apps/kdm/themes/sidux"
	if ( -d "$KDM_THEME" ); then
		printf "USEBACKGROUND=true\nWALLPAPER=\"${FLL_WALLPAPER}\"\n" \
				> ${KDM_OVERRIDE_DIR}/sidux-wallpaper
		printf "USETHEME=true\nTHEME=\"${KDM_THEME}\"\n" \
				> ${KDM_OVERRIDE_DIR}/sidux-theme
		printf "AUTOLOGINUSER=${FLL_LIVE_USER}\nAUTOLOGINAGAIN=true\nAUTOLOGINDELAY=10\n" \
				> ${KDM_OVERRIDE_DIR}/sidux-autologin
	fi

	[ -n "$CUSTOM_DPI" ] &&  sed -i -e "s/\(ServerArgsLocal\=\-nolisten tcp\).*$/\1 \-dpi ${CUSTOM_DPI}/" \
			/etc/kde3/kdm/kdmrc

	update-rc.d kdm start 99 5 . stop 01 0 1 2 3 4 6 . >/dev/null 2>&1
fi

if [ -x /usr/sbin/gdm ]; then
	cp --remove-destination "${FLL_MOUNTPOINT}/etc/gdm/gdm.conf" /etc/gdm/gdm.conf
	sed -i	-e "/^AutomaticLogin\=.*/d" \
		-e "/^AutomaticLoginEnable\=.*/d" \
		-e "s/^\(\[daemon\]$\)/\1\nAutomaticLogin\=${FLL_LIVE_USER}\nAutomaticLoginEnable\=true/" \
			/etc/gdm/gdm.conf

	[ -n "$CUSTOM_DPI" ] && sed -i -e "s/\(command\=\/usr\/bin\/X \-dpi \).*\( -audit.*$\)/\1${CUSTOM_DPI}\2/" \
		/usr/share/gdm/defaults.conf
	
	update-rc.d gdm start 21 5 . stop 01 0 1 2 3 4 6 . >/dev/null 2>&1
fi

###############################################################################
# re-enable printk's and signals
###############################################################################

printf "6\n" > /proc/sys/kernel/printk

trap 2 3 11

exit 0

